In [1]:
import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([[1,2,3],
                 [4,15,6],
                 [7,8,9]])

In [2]:
# 연산
# 배열의 원소를 연산
arr1.mean(axis=0)
arr1.sum(axis=1)

# 배열과 배열의 연산
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2
arr1 % arr2

# 배열과 배열 비교
arr1 == arr2  # 원소 단위로 비교
np.array_equal(arr1, arr2)  # 배열 단위로 비교 (하나라도 다르면 False)


False

In [3]:
# 배열의 형태 변환
arr1.ndim  # 3 X 3
arr1.shape
arr1.reshape((1, 9))  # 원소의 갯수와 변형해서 만들 형태가 일치해야 한다.

arr3 = np.arange(1, 13)
arr3.reshape((4,-1))  # -1은 자동으로 갯수를 일치시켜 준다. -1 대신 3을 사용해도 됨 ㅇㅋ?
# arr3.reshape((3,5)) -> 불가능
arr3.reshape((2, 3, -1)) # 3차원으로 변경할 때 reshape(깊이(axis), 행, 열)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [4]:
# 배열 붙이기, 자르기 -> 2차원 이상에서만 수행 가능 ㅇㅋ?

# 붙이기
np.concatenate((arr1, arr2), axis=0)
arr4 = np.concatenate((arr1, arr2), axis=1)  # axis=0 기본값
# 붙이기 전에 모양 일치하도록

# 자르기
print(arr4)
np.split(arr4, 3, axis=1) # np.split(자를 배열, 자를 개수, 축 정보)
np.split(arr4, 2, axis=1)


[[ 1  2  3  1  2  3]
 [ 4  5  6  4 15  6]
 [ 7  8  9  7  8  9]]


[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 1,  2,  3],
        [ 4, 15,  6],
        [ 7,  8,  9]])]

In [5]:
# 정렬
# 1차원
# 오름차순
np.random.seed(1)
arr5 = np.random.randint(1, 10, 12)
# arr5.sort() # arr5의 원소가 정렬되어 원본에 반영
arr6 = np.sort(arr5)  # 원본은 그대로 유지하면서 정렬된 복사본을 리턴 
np.sort(arr5)
arr5

# 내림차순 -> 오름차순 상태에서 거꾸로 인덱싱
arr6[::-1]

# 2차원
arr7 = arr5.reshape((3,4))
print(arr7)
np.sort(arr7)
np.sort(arr7, axis=0)

[[6 9 6 1]
 [1 2 8 7]
 [3 5 6 3]]


array([[1, 2, 6, 1],
       [3, 5, 6, 3],
       [6, 9, 8, 7]])