In [1]:
import numpy as np

arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

# 합 구하기
# 세로 방향 - axis 0
# 가로 방향 - axis 1
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))

# 평균, 최댓값, 최솟값
print(arr1.mean())
print(arr1.mean(axis=0))
print(arr1.mean(axis=1))

print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))

print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

[15 18 21 24]
[10 26 42]
6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]
12
[ 9 10 11 12]
[ 4  8 12]
1
[1 2 3 4]
[1 5 9]
